kind: Service
apiVersion: v1
metadata:
  name:  demo-service
spec:
  selector:
    name: demo
    version: v1
    stage: dev
  type:   LoadBalancer
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort: 80
